/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './htmls/**/*.{js,jsx,ts,tsx}',
    './test/**/*.{js,jsx,ts,tsx,html}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary: '#18a875',
        'primary-light': '#2ecb98',
        'primary-dark': '#256fd4',
        'primary-muted': 'rgba(24, 168, 117, 0.1)',
        'primary-subtle': 'rgba(24, 168, 117, 0.05)',
        background: '#f8f7f5',
        'background-warm': '#fdf9f6',
        surface: '#ffffff',
        'surface-alt': '#f7f3f0',
        elevated: '#f1edea',
        'text-primary': '#1a1a1a',
        'text-secondary': '#504441',
        'text-muted': '#78716c',
        'text-disabled': '#a8a29e',
        border: '#e7e5e4',
        'border-light': '#d4c3be',
        success: '#00504b',
        error: '#ba1a1a',
        info: '#0066cc',
        'admin-text': '#46291e',
      },
      fontFamily: {
        sans: ['PublicSans_400Regular'],
        display: ['PublicSans_700Bold'],
        medium: ['PublicSans_500Medium'],
        semibold: ['PublicSans_600SemiBold'],
        bold: ['PublicSans_700Bold'],
        extrabold: ['PublicSans_800ExtraBold'],
      },
      spacing: {
        0.5: '2px',
        1: '4px',
        1.5: '6px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        16: '64px',
      },
      borderRadius: {
        sm: '4px',
        DEFAULT: '8px',
        lg: '12px',
        xl: '16px',
      },
    },
  },
  plugins: [],
};
