export type CountryCallingCodeOption = {
  countryName: string;
  iso2: string;
  dialCode: string;
  compactLabel: string;
  label: string;
  value: string;
};

function createCountryOption(countryName: string, iso2: string, dialCode: string): CountryCallingCodeOption {
  return {
    countryName,
    iso2,
    dialCode,
    compactLabel: dialCode,
    label: `${countryName} (${dialCode})`,
    value: dialCode,
  };
}

export const countryCallingCodeOptions: CountryCallingCodeOption[] = [
  createCountryOption('Afghanistan', 'AF', '+93'),
  createCountryOption('Albania', 'AL', '+355'),
  createCountryOption('Algeria', 'DZ', '+213'),
  createCountryOption('American Samoa', 'AS', '+1'),
  createCountryOption('Andorra', 'AD', '+376'),
  createCountryOption('Angola', 'AO', '+244'),
  createCountryOption('Anguilla', 'AI', '+1'),
  createCountryOption('Antigua and Barbuda', 'AG', '+1'),
  createCountryOption('Argentina', 'AR', '+54'),
  createCountryOption('Armenia', 'AM', '+374'),
  createCountryOption('Aruba', 'AW', '+297'),
  createCountryOption('Australia', 'AU', '+61'),
  createCountryOption('Austria', 'AT', '+43'),
  createCountryOption('Azerbaijan', 'AZ', '+994'),
  createCountryOption('Bahamas', 'BS', '+1'),
  createCountryOption('Bahrain', 'BH', '+973'),
  createCountryOption('Bangladesh', 'BD', '+880'),
  createCountryOption('Barbados', 'BB', '+1'),
  createCountryOption('Belarus', 'BY', '+375'),
  createCountryOption('Belgium', 'BE', '+32'),
  createCountryOption('Belize', 'BZ', '+501'),
  createCountryOption('Benin', 'BJ', '+229'),
  createCountryOption('Bermuda', 'BM', '+1'),
  createCountryOption('Bhutan', 'BT', '+975'),
  createCountryOption('Bolivia', 'BO', '+591'),
  createCountryOption('Bosnia and Herzegovina', 'BA', '+387'),
  createCountryOption('Botswana', 'BW', '+267'),
  createCountryOption('Brazil', 'BR', '+55'),
  createCountryOption('British Virgin Islands', 'VG', '+1'),
  createCountryOption('Brunei', 'BN', '+673'),
  createCountryOption('Bulgaria', 'BG', '+359'),
  createCountryOption('Burkina Faso', 'BF', '+226'),
  createCountryOption('Burundi', 'BI', '+257'),
  createCountryOption('Cambodia', 'KH', '+855'),
  createCountryOption('Cameroon', 'CM', '+237'),
  createCountryOption('Canada', 'CA', '+1'),
  createCountryOption('Cape Verde', 'CV', '+238'),
  createCountryOption('Cayman Islands', 'KY', '+1'),
  createCountryOption('Central African Republic', 'CF', '+236'),
  createCountryOption('Chad', 'TD', '+235'),
  createCountryOption('Chile', 'CL', '+56'),
  createCountryOption('China', 'CN', '+86'),
  createCountryOption('Colombia', 'CO', '+57'),
  createCountryOption('Comoros', 'KM', '+269'),
  createCountryOption('Congo', 'CG', '+242'),
  createCountryOption('Cook Islands', 'CK', '+682'),
  createCountryOption('Costa Rica', 'CR', '+506'),
  createCountryOption("Cote d'Ivoire", 'CI', '+225'),
  createCountryOption('Croatia', 'HR', '+385'),
  createCountryOption('Cuba', 'CU', '+53'),
  createCountryOption('Curacao', 'CW', '+599'),
  createCountryOption('Cyprus', 'CY', '+357'),
  createCountryOption('Czech Republic', 'CZ', '+420'),
  createCountryOption('Democratic Republic of the Congo', 'CD', '+243'),
  createCountryOption('Denmark', 'DK', '+45'),
  createCountryOption('Djibouti', 'DJ', '+253'),
  createCountryOption('Dominica', 'DM', '+1'),
  createCountryOption('Dominican Republic', 'DO', '+1'),
  createCountryOption('Ecuador', 'EC', '+593'),
  createCountryOption('Egypt', 'EG', '+20'),
  createCountryOption('El Salvador', 'SV', '+503'),
  createCountryOption('Equatorial Guinea', 'GQ', '+240'),
  createCountryOption('Eritrea', 'ER', '+291'),
  createCountryOption('Estonia', 'EE', '+372'),
  createCountryOption('Eswatini', 'SZ', '+268'),
  createCountryOption('Ethiopia', 'ET', '+251'),
  createCountryOption('Faroe Islands', 'FO', '+298'),
  createCountryOption('Fiji', 'FJ', '+679'),
  createCountryOption('Finland', 'FI', '+358'),
  createCountryOption('France', 'FR', '+33'),
  createCountryOption('French Guiana', 'GF', '+594'),
  createCountryOption('French Polynesia', 'PF', '+689'),
  createCountryOption('Gabon', 'GA', '+241'),
  createCountryOption('Gambia', 'GM', '+220'),
  createCountryOption('Georgia', 'GE', '+995'),
  createCountryOption('Germany', 'DE', '+49'),
  createCountryOption('Ghana', 'GH', '+233'),
  createCountryOption('Gibraltar', 'GI', '+350'),
  createCountryOption('Greece', 'GR', '+30'),
  createCountryOption('Greenland', 'GL', '+299'),
  createCountryOption('Grenada', 'GD', '+1'),
  createCountryOption('Guadeloupe', 'GP', '+590'),
  createCountryOption('Guam', 'GU', '+1'),
  createCountryOption('Guatemala', 'GT', '+502'),
  createCountryOption('Guernsey', 'GG', '+44'),
  createCountryOption('Guinea', 'GN', '+224'),
  createCountryOption('Guinea-Bissau', 'GW', '+245'),
  createCountryOption('Guyana', 'GY', '+592'),
  createCountryOption('Haiti', 'HT', '+509'),
  createCountryOption('Honduras', 'HN', '+504'),
  createCountryOption('Hong Kong', 'HK', '+852'),
  createCountryOption('Hungary', 'HU', '+36'),
  createCountryOption('Iceland', 'IS', '+354'),
  createCountryOption('India', 'IN', '+91'),
  createCountryOption('Indonesia', 'ID', '+62'),
  createCountryOption('Iran', 'IR', '+98'),
  createCountryOption('Iraq', 'IQ', '+964'),
  createCountryOption('Ireland', 'IE', '+353'),
  createCountryOption('Isle of Man', 'IM', '+44'),
  createCountryOption('Israel', 'IL', '+972'),
  createCountryOption('Italy', 'IT', '+39'),
  createCountryOption('Jamaica', 'JM', '+1'),
  createCountryOption('Japan', 'JP', '+81'),
  createCountryOption('Jersey', 'JE', '+44'),
  createCountryOption('Jordan', 'JO', '+962'),
  createCountryOption('Kazakhstan', 'KZ', '+7'),
  createCountryOption('Kenya', 'KE', '+254'),
  createCountryOption('Kiribati', 'KI', '+686'),
  createCountryOption('Kosovo', 'XK', '+383'),
  createCountryOption('Kuwait', 'KW', '+965'),
  createCountryOption('Kyrgyzstan', 'KG', '+996'),
  createCountryOption('Laos', 'LA', '+856'),
  createCountryOption('Latvia', 'LV', '+371'),
  createCountryOption('Lebanon', 'LB', '+961'),
  createCountryOption('Lesotho', 'LS', '+266'),
  createCountryOption('Liberia', 'LR', '+231'),
  createCountryOption('Libya', 'LY', '+218'),
  createCountryOption('Liechtenstein', 'LI', '+423'),
  createCountryOption('Lithuania', 'LT', '+370'),
  createCountryOption('Luxembourg', 'LU', '+352'),
  createCountryOption('Macau', 'MO', '+853'),
  createCountryOption('Madagascar', 'MG', '+261'),
  createCountryOption('Malawi', 'MW', '+265'),
  createCountryOption('Malaysia', 'MY', '+60'),
  createCountryOption('Maldives', 'MV', '+960'),
  createCountryOption('Mali', 'ML', '+223'),
  createCountryOption('Malta', 'MT', '+356'),
  createCountryOption('Marshall Islands', 'MH', '+692'),
  createCountryOption('Martinique', 'MQ', '+596'),
  createCountryOption('Mauritania', 'MR', '+222'),
  createCountryOption('Mauritius', 'MU', '+230'),
  createCountryOption('Mayotte', 'YT', '+262'),
  createCountryOption('Mexico', 'MX', '+52'),
  createCountryOption('Micronesia', 'FM', '+691'),
  createCountryOption('Moldova', 'MD', '+373'),
  createCountryOption('Monaco', 'MC', '+377'),
  createCountryOption('Mongolia', 'MN', '+976'),
  createCountryOption('Montenegro', 'ME', '+382'),
  createCountryOption('Montserrat', 'MS', '+1'),
  createCountryOption('Morocco', 'MA', '+212'),
  createCountryOption('Mozambique', 'MZ', '+258'),
  createCountryOption('Myanmar', 'MM', '+95'),
  createCountryOption('Namibia', 'NA', '+264'),
  createCountryOption('Nauru', 'NR', '+674'),
  createCountryOption('Nepal', 'NP', '+977'),
  createCountryOption('Netherlands', 'NL', '+31'),
  createCountryOption('New Caledonia', 'NC', '+687'),
  createCountryOption('New Zealand', 'NZ', '+64'),
  createCountryOption('Nicaragua', 'NI', '+505'),
  createCountryOption('Niger', 'NE', '+227'),
  createCountryOption('Nigeria', 'NG', '+234'),
  createCountryOption('North Korea', 'KP', '+850'),
  createCountryOption('North Macedonia', 'MK', '+389'),
  createCountryOption('Northern Mariana Islands', 'MP', '+1'),
  createCountryOption('Norway', 'NO', '+47'),
  createCountryOption('Oman', 'OM', '+968'),
  createCountryOption('Pakistan', 'PK', '+92'),
  createCountryOption('Palau', 'PW', '+680'),
  createCountryOption('Palestine', 'PS', '+970'),
  createCountryOption('Panama', 'PA', '+507'),
  createCountryOption('Papua New Guinea', 'PG', '+675'),
  createCountryOption('Paraguay', 'PY', '+595'),
  createCountryOption('Peru', 'PE', '+51'),
  createCountryOption('Philippines', 'PH', '+63'),
  createCountryOption('Poland', 'PL', '+48'),
  createCountryOption('Portugal', 'PT', '+351'),
  createCountryOption('Puerto Rico', 'PR', '+1'),
  createCountryOption('Qatar', 'QA', '+974'),
  createCountryOption('Reunion', 'RE', '+262'),
  createCountryOption('Romania', 'RO', '+40'),
  createCountryOption('Russia', 'RU', '+7'),
  createCountryOption('Rwanda', 'RW', '+250'),
  createCountryOption('Saint Kitts and Nevis', 'KN', '+1'),
  createCountryOption('Saint Lucia', 'LC', '+1'),
  createCountryOption('Saint Martin', 'MF', '+590'),
  createCountryOption('Saint Pierre and Miquelon', 'PM', '+508'),
  createCountryOption('Saint Vincent and the Grenadines', 'VC', '+1'),
  createCountryOption('Samoa', 'WS', '+685'),
  createCountryOption('San Marino', 'SM', '+378'),
  createCountryOption('Sao Tome and Principe', 'ST', '+239'),
  createCountryOption('Saudi Arabia', 'SA', '+966'),
  createCountryOption('Senegal', 'SN', '+221'),
  createCountryOption('Serbia', 'RS', '+381'),
  createCountryOption('Seychelles', 'SC', '+248'),
  createCountryOption('Sierra Leone', 'SL', '+232'),
  createCountryOption('Singapore', 'SG', '+65'),
  createCountryOption('Sint Maarten', 'SX', '+1'),
  createCountryOption('Slovakia', 'SK', '+421'),
  createCountryOption('Slovenia', 'SI', '+386'),
  createCountryOption('Solomon Islands', 'SB', '+677'),
  createCountryOption('Somalia', 'SO', '+252'),
  createCountryOption('South Africa', 'ZA', '+27'),
  createCountryOption('South Korea', 'KR', '+82'),
  createCountryOption('South Sudan', 'SS', '+211'),
  createCountryOption('Spain', 'ES', '+34'),
  createCountryOption('Sri Lanka', 'LK', '+94'),
  createCountryOption('Sudan', 'SD', '+249'),
  createCountryOption('Suriname', 'SR', '+597'),
  createCountryOption('Sweden', 'SE', '+46'),
  createCountryOption('Switzerland', 'CH', '+41'),
  createCountryOption('Syria', 'SY', '+963'),
  createCountryOption('Taiwan', 'TW', '+886'),
  createCountryOption('Tajikistan', 'TJ', '+992'),
  createCountryOption('Tanzania', 'TZ', '+255'),
  createCountryOption('Thailand', 'TH', '+66'),
  createCountryOption('Timor-Leste', 'TL', '+670'),
  createCountryOption('Togo', 'TG', '+228'),
  createCountryOption('Tonga', 'TO', '+676'),
  createCountryOption('Trinidad and Tobago', 'TT', '+1'),
  createCountryOption('Tunisia', 'TN', '+216'),
  createCountryOption('Turkey', 'TR', '+90'),
  createCountryOption('Turkmenistan', 'TM', '+993'),
  createCountryOption('Turks and Caicos Islands', 'TC', '+1'),
  createCountryOption('Tuvalu', 'TV', '+688'),
  createCountryOption('U.S. Virgin Islands', 'VI', '+1'),
  createCountryOption('Uganda', 'UG', '+256'),
  createCountryOption('Ukraine', 'UA', '+380'),
  createCountryOption('United Arab Emirates', 'AE', '+971'),
  createCountryOption('United Kingdom', 'GB', '+44'),
  createCountryOption('United States', 'US', '+1'),
  createCountryOption('Uruguay', 'UY', '+598'),
  createCountryOption('Uzbekistan', 'UZ', '+998'),
  createCountryOption('Vanuatu', 'VU', '+678'),
  createCountryOption('Vatican City', 'VA', '+379'),
  createCountryOption('Venezuela', 'VE', '+58'),
  createCountryOption('Vietnam', 'VN', '+84'),
  createCountryOption('Yemen', 'YE', '+967'),
  createCountryOption('Zambia', 'ZM', '+260'),
  createCountryOption('Zimbabwe', 'ZW', '+263'),
];
