import type { Permission, UserRole } from '@/src/types/app';

export const rolePermissionMap: Record<UserRole, Permission[]> = {
  admin: [
    'registration.manage',
    'kyc.approve',
    'profile_requests.manage',
    'profile.manage',
    'directory.view',
    'directory.manage',
    'user.manage',
    'users.view',
    'users.edit',
    'users.delete',
    'users.block',
    'events.view',
    'events.manage',
    'event.manage',
    'event.photo_upload',
    'events.attendance',
    'donations.view',
    'donations.manage',
    'transactions.manage',
    'analytics.view',
    'roles.manage',
    'admins.manage',
    'notifications.manage',
    'communication.manage',
    'chats.manage',
    'chat.manage',
    'promotions.view',
    'promotions.manage',
    'matrimony.manage',
    'publications.manage',
  ],
  member: ['profile.manage', 'directory.view', 'events.view', 'donations.view'],
  community_member: ['profile.manage', 'directory.view', 'events.view', 'donations.view'],
  user: ['events.view', 'directory.view'],
  trustee: ['profile.manage', 'directory.view', 'events.view', 'donations.view'],
};

export const permissionAccessMap: Record<Permission, UserRole[]> = {
  'registration.manage': ['admin'],
  'kyc.approve': ['admin'],
  'profile_requests.manage': ['admin'],
  'marksheet.view': ['admin'],
  'marksheet.manage': ['admin'],
  'children_education.view': ['admin'],
  'children_education.manage': ['admin'],
  'profile.manage': ['admin', 'member', 'community_member', 'user', 'trustee'],
  'directory.view': ['admin', 'member', 'community_member', 'user', 'trustee'],
  'directory.manage': ['admin'],
  'user.manage': ['admin'],
  'users.view': ['admin'],
  'phone.view': [],
  'users.edit': ['admin'],
  'users.delete': ['admin'],
  'users.block': ['admin'],
  'events.view': ['admin', 'member', 'community_member', 'user', 'trustee'],
  'events.manage': ['admin'],
  'event.manage': ['admin'],
  'event.photo_upload': ['admin'],
  'events.attendance': ['admin'],
  'donations.view': ['admin', 'member', 'community_member', 'user', 'trustee'],
  'donations.manage': ['admin'],
  'transactions.manage': ['admin'],
  'analytics.view': ['admin'],
  'roles.manage': ['admin'],
  'admins.manage': ['admin'],
  'notifications.manage': ['admin'],
  'communication.manage': ['admin'],
  'chats.manage': ['admin'],
  'chat.manage': ['admin'],
  'promotions.view': ['admin'],
  'promotions.manage': ['admin'],
  'matrimony.manage': ['admin'],
  'publications.manage': ['admin'],
};
